Remove DoS attack mitigation and add ack.
chris-wood/draft-amjad-cfrg-partially-blind-rsa pull request #26
Opened 2023-06-19 17:12 UTC by kwlyeo

2023-06-19 20:49 UTC, Guss123 approved these changes

2023-06-19 20:49 UTC, Guss123 approved these changes

2023-06-21 11:29 UTC, chris-wood requested changes

2023-06-21 11:29 UTC, chris-wood commented on draft-amjad-cfrg-partially-blind-rsa.md
> -SHOULD use one of the protocol variants in {{RSABSSA}} with distinct keys for each metadata value.
I think we should keep this advice. There's no strong reason to use this variant if there's few metadata choices.

2023-06-21 19:44 UTC, merged